# Generated by Django 5.0 on 2024-01-07 07:11

import Profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('thumbnail', models.ImageField(upload_to=Profile.models.Project.dynamic_photo_path)),
                ('featured', models.BooleanField(default=False)),
                ('brief', models.CharField(max_length=240)),
                ('description', models.CharField(max_length=1600)),
                ('date', models.DateField()),
                ('topics', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('instance', models.CharField(max_length=64)),
            ],
        ),
    ]
