# Generated by Django 5.0 on 2024-01-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_alter_project_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='template_name',
            field=models.CharField(default='test', max_length=16),
            preserve_default=False,
        ),
    ]
